apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    build.appstudio.openshift.io/application: my-application
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: python
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: python
  namespace: relimele
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_openshift_hac-dev
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/openshift/hac-dev
